### ISSUE TITLE
Migrate website here

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis.org#1]
@mcgredonps I meant to chat with you about this in person at IITSEC to get your thoughts. 

A few months ago I saw that the www.open-dis.org domain name was available so I registered it. I'd be happy to either transfer it into your name or keep paying the annual fee myself.

I thought the new address could eventually replace http://open-dis.sourceforge.net.

Using GitHub Pages tech we could host the website content in this git repository.

**Comment by leif81** [comment]
Ok the DNS configuration for open-dis.org is working now.

If you navigate to http://www.open-dis.org you'll see the rendered README.md. Anytime that file is modified the website will reflect the change automatically. Too easy!

**Comment by mcgredonps** [comment]
Well, cool. Sounds like a great move. I’m trying to get completely off of
source forge.

I’m messing around a bit with the Javascript implementation on the server side,
and starting off with a nodejs application that displays some stats on the DIS traffic
on the network. It should be possible to write a data logger that stuffs all the DIS
traffic the server sees into a mongo database.

Is there any chance you could send me those intercom PDU captures we discussed?
I’m poking around a little bit in the W3C WebRTC standard. What they did looks
convoluted, or optimized for dealing with audio at a higher level of abstraction
than I’d like, but I think it’s possible to extract the u-law data from a laptop
mic and insert it into a signal PDU. Looking at the PDU, I don’t see field that
specifies order or sequence for the data. Does everyone just rely on the timestamp
in the header for that?

There was a paper at IITSEC on the Blended Warrior 2015 exercise, and the presenter
mentioned the possibility of releasing the captured exercise DIS PDUs. I’ll drop him
a line and see if I can get access to them.


On Dec 2, 2016, at 10:19 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcgredonps<https://github.com/mcgredonps> I meant to chat with you about this in person at IITSEC to get your thoughts.

A few months ago I saw that the www.open-dis.org<http://www.open-dis.org/> domain name was available so I registered it. I'd be happy to either transfer it into your name or keep paying the annual fee myself.

I thought the address could eventually replace open-dis.sourceforge.com<http://open-dis.sourceforge.com>.

Using GitHub Pages tech we could host the website content in this git repository.

**Comment by leif81** [comment]
@mcgredonps Hmm I sent a zip with some pdu's to your `mcgredo at nps.edu` address a week or so ago.  Didn't get it I presume? I'll can retry this time using my Google Drive to share them to you.

**Comment by leif81** [comment]
I pushed a couple commits to populate the basics of the main page. It's very minimal right now, but wanted to get something up there instead of just "hello world" :)

**Comment by leif81** [comment]
I've done some more work to the website. I've migrated the majority of the content over from http://open-dis.sourceforge.net. And I applied a theme to make it a little more jazzy.

Take a look here: http://open-dis.org

**Comment by leif81** [comment]
@mcgredonps Once you're Ok with the new webpage, we should discuss a migration plan to turn off the sourceforge website and project page. What do you think?

**Comment by mcgredonps** [comment]
Sounds good, especially if it gets up and at least initially run before I/ITSEC

________________________________

**Comment by leif81** [comment]
I'm going to close this since the content from the old site has been migrated. If I missed anything we can open an issue.
