### ISSUE TITLE
Redirect http://open-dis.sourceforge.net to http://open-dis.org

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis.org#2]
As part of moving off of SourceForge (open-dis/open-dis-java#52), we should replace the content on the old website (http://open-dis.sourceforge.net) with a redirect to the new website (http://open-dis.org). 

I don't think I have access to the SourceForge project, @mcgredonps could you do this?

**Comment by mcgredonps** [comment]
Sure, I'll try to get it done this AM.

________________________________

**Comment by mcgredonps** [comment]
OK, the change made. It's using sftp to upload html files. I put in a reload lasting 5 sec and some text on the page.


http://open-dis.sourceforge.net/Open-DIS.html

Open-DIS<http://open-dis.sourceforge.net/Open-DIS.html>
open-dis.sourceforge.net
Open-DIS: An Open Source Implementation of the Distributed Interactive Simulation Protocol. DIS is one of the most widely used protocols in Department of Defense ...




________________________________

**Comment by leif81** [comment]
Great! I tested it and the redirect is working.

I'll keep an eye on the Google Analytics stats. I expect we'll see an uptick in page views on open-dis.org soon.

![open-dis org-stats](https://user-images.githubusercontent.com/494426/36793657-f4fae72a-1c6b-11e8-8def-3bc8362f7e79.PNG)
